### ISSUE TITLE
Sentence Case - HTML Components

### ISSUE THREAD

**Issue by katierik** [patternfly/patternfly-org#944]
Capturing as many of these in one issue as possible!

"About Modal Box" vs "About modal box"
![image](https://user-images.githubusercontent.com/23172038/56829516-ed928700-6831-11e9-9884-98c3c7c01a9e.png)

Also on the about modal page:
![Xnip2019-04-26_14-46-03](https://user-images.githubusercontent.com/23172038/56829574-1c106200-6832-11e9-801f-ee18aa8e7109.jpg)
and
![Xnip2019-04-26_14-47-09](https://user-images.githubusercontent.com/23172038/56829607-35191300-6832-11e9-83c2-595735612d67.jpg)

**Comment by katierik** [comment]
HTML Accordion page
![Xnip2019-04-26_14-48-16](https://user-images.githubusercontent.com/23172038/56829666-62fe5780-6832-11e9-84c8-ebc6e34eb6e9.jpg)

![Xnip2019-04-26_14-49-08](https://user-images.githubusercontent.com/23172038/56829714-7f01f900-6832-11e9-91bb-528777b0614e.jpg)

![Xnip2019-04-26_14-49-53](https://user-images.githubusercontent.com/23172038/56829742-950fb980-6832-11e9-9d50-d23844b20ada.jpg)

**Comment by katierik** [comment]
Alert page
![image](https://user-images.githubusercontent.com/23172038/56829887-e91a9e00-6832-11e9-88a4-57c3f7e53e0b.png)
![image](https://user-images.githubusercontent.com/23172038/56829915-fc2d6e00-6832-11e9-92f4-a2e98c159c8c.png)
![image](https://user-images.githubusercontent.com/23172038/56829977-20894a80-6833-11e9-8a5a-b6ac8131a5f5.png)

**Comment by katierik** [comment]
There are so many more. Every single page has a lot of sentence case issues that would probably be best served by someone spotting & fixing at the same time.

**Comment by dgutride** [comment]
The main nav and top headers have been fixed - recommend moving remainder to post-rc for fix.

**Comment by rachael-phillips** [comment]
@dgutride I just spoke with Stacy, and she is working on this for us now

**Comment by redallen** [comment]
Where is there still sentence casing that needs fixing? I think this is mostly taken care of.

**Comment by dgutride** [comment]
I think we finished this one @redallen  - @stacymcauliffe  - can we close it?

**Comment by stacymcauliffe** [comment]
Still seeing a few places we've still got sentence case -- 

Documentation - CSS Variables, React Tokens, Props (see examples below) 

![image](https://user-images.githubusercontent.com/35926653/60292897-24e1ea80-98ec-11e9-8401-45f0d044117c.png)

![image](https://user-images.githubusercontent.com/35926653/60292916-2ca18f00-98ec-11e9-8d3b-34323664f26c.png)

![image](https://user-images.githubusercontent.com/35926653/60292984-43e07c80-98ec-11e9-8937-a8f2190a7a83.png)

**Comment by dgutride** [comment]
We'll leave it open - thanks for the update @stacymcauliffe.  Unassigning @redallen
